sudo: false
    
language: node_js

node_js:
      - "4.1"

services:
    - docker

before_install:
    - docker build -t jekkos/opensourcepos .
    - docker run -d jekkos/opensourcepos 

script:
    - docker exec -t -i $(docker ps | tail -n 1 | cut -d' ' -f1) /bin/sh -c "wget --retry-connrefused --tries=5 -q --waitretry=3 --spider http://localhost/index.php && cd /app && grunt mochaWebdriver:test" 
