sudo: false

services:
    - docker

before_install:
    - docker-compose build
    - docker-compose up -d

script:
    - docker-wait opensourcepos_php_1

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push jekkos/opensourcepos
