sudo: required

language: node_js

node_js:
    - 0.10

services:
    - docker

before_install:
    - docker build -t jekkos/opensourcepos .

script:
    - docker run -i -p 127.0.0.1:80:80 jekkos/opensourcepos /bin/sh -c "cd /app; grunt mochaWebdriver:test"
