version: '2.2'

include:
  - docker/docker-mysql.yml

services:
    ospos:
        build:
            context: .
            args:
              - USERID=${USERID}
              - GROUPID=${GROUPID}
            target: ospos_dev
        container_name: ospos_dev
        restart: always
        user: "${USERID}:${GROUPID}"
        depends_on:
          - mysql
        ports:
          - "80:80"
        networks:
          - app_net
        volumes:
          - .:/app
        environment:
          - CI_ENVIRONMENT=development
          - MYSQL_USERNAME=admin
          - MYSQL_PASSWORD=pointofsale
          - MYSQL_DB_NAME=ospos
          - MYSQL_HOST_NAME=mysql
          - PHP_TIMEZONE=UTC
          - XDEBUG_CONFIG=client_host=172.17.0.1
