version: '2'

volumes:
    ospos:
        driver: local
  
services:
    test: 
        build:
            context: .
            dockerfile: Dockerfile.test
    php:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - mysql
        ports:
            - "80:80"
        volumes:
            - ospos:/var/www/html
            - ospos:/app
        environment:
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=pointofsale
            - MYSQL_DATABASE=ospos
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=pointofsale
        ports:
            - "3306:3306"
        volumes:
            - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
