version: '3.4'
  
services:
    test: 
        build:
            context: .
            target: ospos_test
        depends_on: 
          - mysql
        container_name: ospos_test
        environment:
          - CI_ENV=testing
          - ENCRYPTION_KEY=
          - MYSQL_HOST_NAME=127.0.0.1
          - MYSQL_DATABASE=ospos
          - MYSQL_USERNAME=admin
          - MYSQL_PASSWORD=pointofsale
        ports:
          - "80:80"

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        volumes:
          - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
          - MYSQL_ROOT_PASSWORD=pointofsale
          - MYSQL_DATABASE=ospos
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=pointofsale
